In [1]:
import numpy as np

In [2]:
from scipy import special as sp
a=sp.exp2(2)
b=sp.sindg(20)


In [3]:
from scipy import integrate as it
c=it.quad(lambda x: np.power(x,2),0,1)
c

(0.33333333333333337, 3.700743415417189e-15)

In [5]:
from scipy import fftpack as ff
a=np.array(range(5))
b=ff.fft(a)
b

array([10. -0.j        , -2.5+3.4409548j , -2.5+0.81229924j,
       -2.5-0.81229924j, -2.5-3.4409548j ])

In [10]:
from scipy import linalg as lg
a=np.array(range(1,5),ndmin=2)
a=a.reshape((2,2))
b=lg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
from scipy import interpolate as ip

In [19]:
a=np.poly1d(range(4))
print(a)
print(a*2)
print(a.c,a.r)
print(a.integ(k=2))
print(a.deriv())

   2
1 x + 2 x + 3
   2
2 x + 4 x + 6
[1 2 3] [-1.+1.41421356j -1.-1.41421356j]
        3     2
0.3333 x + 1 x + 3 x + 2
 
2 x + 2


In [21]:
print(sp.radian(60,60,60))

1.0649417319252068
